### ISSUE TITLE
Sortierungen von A-Z (z.B. in der Spaltenauswahl) und Sortierung von 1-10 und nicht 1,10,2,3,4,5,

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#11]

**Comment by jziehmann** [comment]
Das wäre schön. Das kann ich aber nicht umsetzen. Die Sortierung ergibt sich aus der Standard-Spalten-Reihenfolge, die ich definiere. Wenn ich die alphabetisch sortiere, sind auch die Spalten in der Tabelle alphabetisch angeordnet und nicht nach Wichtigkeit. Außerdem bekomme ich dann Probleme in anderen Sprachen.

**Comment by jziehmann** [comment]
Ich habe doch einen Weg gefunden, die Namen in der Spaltenauswahl alphabetisch zu sortieren

**Comment by HenningReiter** [comment]
Coole Sache, top
