### ISSUE TITLE
In der ersten übersicht erscheine eine Zeile: Meine Projekte, Aufgaben,.... die sollte in jeder Ansicht zu sehen sein!

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#12]

**Comment by jziehmann** [comment]
Warum? Du kommst jederzeit dahin zurück, wenn du links oben auf das 8.2-Logo oder "Project Database" klickst.

**Comment by HenningReiter** [comment]
Für meinen Geschmack muss man noch zu viele Klicks machen. Wenn ich mich in einem Projekt bewege und dann z. b. zum Windpark oder einer Anlage gehe und dann wieder zum Projekt möchte, muss ich mich wieder von vorne durchklicken bis ich wieder beim Projekt bin. Oder habe ich was übersehen....

**Comment by jziehmann** [comment]
Kannst du nicht einfach den "Zurück"-Knopf nutzen oder ein paar mal Alt-Links drücken
