### ISSUE TITLE
Projektkarte

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#19]
Kannst du eine Karte mit allen offenen Projekten einer 8.2 Einheit erstellen? Für die Planung von Reisen wäre das sehr hilfreich um Projekte zusammen abzuarbeiten. Ein Kontrollkästchen "Standort geprüft" nimmt das Projekt aus der Karte...

**Comment by jziehmann** [comment]
Unter https://pdb.8p2-data.de/home?tab=map gibt es bereits eine Karte aller Standorte aus allen Projekten, die dir zugeordnet sind. Man kann dort nach Wunschterminen filtern. 
Ich könnte Standorte herausfiltern oder farblich anders darstellen, bei denen die Einsatzplanung fertig ist.

**Comment by HenningReiter** [comment]
Genau, sie ist mir zugeordnet.
Als Planer möchte ich aber eine Karte aller Projekte sehen, die angefragt sind, die wir angeboten haben oder beauftragt haben, ohne dass ich eine extra Zuordnung machen muss. Es sollte eine Unterscheidung für meine Projekte und der Projekte der Firma geben.
Beauftragte (grün) und angebotene (orange) bzw. angefragte (rot) Projekte farblich gekennzeichnet und auswählbar in der Ansicht wäre super.

**Comment by jziehmann** [comment]
Ich hatte dir ja alle Projekte eurer Firma zugeordnet. Ich stelle jetzt angebotene Projekte in blau, beauftragte in grün und überfällige in rot dar.

**Comment by jziehmann** [comment]
![image](https://github.com/user-attachments/assets/3dcf63ac-c1b3-4ca0-9f58-fd71c0da8a3b)
