### ISSUE TITLE
Arbeitszeit

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#20]
Die Arbeitszeit kann nicht über die Tagesgrenze hinaus eingetragen werden.

z.B.: 
Beginn: 01.01. 22:00 uhr
Ende : 02.01. 01:00 uhr

**Comment by jziehmann** [comment]
Doch, das geht. Ich überprüfe allerdings, ob das Ende vor dem Start liegt und korrigiere es ggf.
Wenn du beim Enddatum zuerst den zweiten Januar auswählst, kannst du die Uhrzeit auf 1:00 stellen. Andersherum greift die Autokorrektur.

![image](https://github.com/user-attachments/assets/a4fde1c5-7a94-464e-93f3-5c45fa413aa9)

**Comment by HenningReiter** [comment]
Die Stunde am neuen Tag wird aber nicht in der Tagesansicht des neuen Tags angezeigt....
