### ISSUE TITLE
Arbeitszeit

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#21]
Die Arbeitszeit kann nicht mit 00:00 Uhr begonnen oder beendet werden.

Es muss mit 23:59 aufgehört und mit 00:01 Uhr angefangen werden.

**Comment by jziehmann** [comment]
Das kann ich nicht nachvollziehen. Ich kann 00:00 als Startzeit eintragen.

![image](https://github.com/user-attachments/assets/0775c128-9b2c-4170-ad7f-f9c2260b48b0)
