### ISSUE TITLE
Dokumente hinzufügen

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#22]
Kannst du das hinzufügen von Dokumenten direkt in der Eingabemaske ermöglichen?

Beispiel: ich gebe einen Mietwagen bei einer Reise ein und in der Maske wo ich die Daten für den Mietwagen eintrage, kann auch gleich die Rechnung hochgeladen werden.

Momentan muss man erst die Daten eingeben, speichern, dann die Position nochmal öffnen und die Rechnung anhängen.

**Comment by jziehmann** [comment]
Der Datensatz muss erst gespeichert werden, damit ich Dateien anhängen kann. Ich habe das Verfahren jetzt so geändert, dass man nach der Eingabe direkt in der Reisekosten-Position landet. Man muss sie also nicht nochmal öffnen. Das spart immerhin eine Suche in der Liste und einen Klick.
