### ISSUE TITLE
Zahlungsmethode

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#23]
Kannst du noch die Zahlungsmethode "Privatauslage" einfügen? Dann ist die Zelle nicht leer in der Übersicht.

**Comment by jziehmann** [comment]
Das ist nicht so einfach. Die Zahlungsmethoden könnt ihr ja frei definieren. Ich müsste dann bei "Privatauslage" wissen, dass ich sie  ersetzen muss. Deshalb würde ich es gerne so lassen. "Kein Eintrag" bedeutet dann "Nicht von der Firma bezahlt -> Also erstatten"
