### ISSUE TITLE
Reisekostenpositionen

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#24]
Kannst du in der Ansicht "Reisekostenpositionen" noch ein Dateisymbol hinzufügen, wenn man für die Einzelposition schon eine Rechnung hinterlegt hat?

Dann sieht man auf den ersten Blick, wo ggf. noch Anhänge fehlen.

**Comment by jziehmann** [comment]
Ich habe jetzt eine Spalte "Anzahl Anhänge" hinzugefügt.
