### ISSUE TITLE
WKP unterscheidung RB und MA

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#26]
Hallo Jochen,

es wäre gut bei den Anlagen ein Datumsfeld für Rotorblätter und ein Datumsfeld für Maschine..

Teilweise sind die Daten auseinander, gerade im Weiterbetrieb unterscheiden sie sich.

Viele Grüße
Henning

**Comment by jziehmann** [comment]
Welches Datum willst du bei Anlagen für Rotorblätter und für die Maschine erfassen?

**Comment by HenningReiter** [comment]
![Screenshot 2024-10-24 111055](https://github.com/user-attachments/assets/5cab5edb-4775-446e-900c-f04d38375b1e)
Nur eine Unterscheidung für:

- Nächste Wiederkehrende Prüfung Maschine: 31.07.2025
- Nächste Wiederkehrende Prüfung Rotorblätter: 31.03.2025

Weil die beiden Kompnenten oft in unterschiedlichen Monaten geprüft werden und wir das in den Berichten auch unterschiedlich aufführen welche Komponente wann dran ist mit der Prüfung.
