### ISSUE TITLE
Urlaubsanträge - Automatische Berechnung der genommenen Tage

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#29]
Die Trennung von Anfangs- und Endzeitpunkt von der Anzahl der genommenen Tage führt regelmäßig zu falschen Urlaubsanträgen. Darüber hinaus sollte es auch nicht möglich sein, dass das Enddatum vor dem Anfangsdatum liegt. 

Lösungsidee:
Ideal wäre eine automatische Ermittlung der freien Tage auf Basis eines Mandantenkalenders, in den Feiertage oder Betriebsferien eingetragen werden. Dieser müsste per Default bei jedem Mitarbeiter hinterlegt, aber dort individualisierbar sein, falls es Mitarbeiter in anderen Ländern gibt, die aber zu diesem Mandanten gehören. 
![grafik](https://github.com/user-attachments/assets/4500762b-9eae-4043-b644-925ca2f6f187)

**Comment by jziehmann** [comment]
In der nächsten Version werden die Urlaubstage automatisch berechnet.
