### ISSUE TITLE
Live-Tracken Arbeitszeiten: Sonstiges als Default für Tätigkeiten

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#30]
Hallo Jochen, 

aktuell ist Akquise als Default für Tätigkeiten eingestellt. Um ggf. Verzerrungen zu vermeiden, würde ich gerne Sonstiges als Default vorschlagen. Ist das möglich oder streng alphabetisch vorbelegt?

Viele Grüße
Niklas

**Comment by jziehmann** [comment]
Eigentlich ist standardmäßig gar keine Tätigkeit voreingestellt. Bisher sind diese vom Benutzer frei definierbar. Deshalb ist es schwierig, "Sonstiges" als Standard zu setzen.
