### ISSUE TITLE
Einsatzplanung

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#32]
Bei Henning werden die "Ausrüstungsarten" immer wieder angezeigt, obwohl er diese abgewählt hat. Bei mir (Linda) ist die Einstellung einmal rausgenommen und seitdem speichert er diese.

**Comment by jziehmann** [comment]
Das kann ich nicht nachvollziehen. Welchen Browser nutzt Henning? Wahrscheinlich müsste ich direkt bei Henning in die Debug-Ausgaben schauen.

**Comment by jziehmann** [comment]
Das lag daran, dass Henning im Firefox eingestellt hatte, beim Beenden alle Webdaten zu löschen
