### ISSUE TITLE
Einsatzplanung / Verschieben

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#33]
Können die die Option der Terminverschiebung direkt in der Einsatzplanung auf die Rolle "Vertrieb" legen?
Auf jeden Mitarbeiter wäre es zu viel Gewühle (wenn alle Termine ändern können) und Management ist keine Rolle für die Mitarbeiter im Vertrieb.

**Comment by jziehmann** [comment]
Das können wir Morgen besprechen.
