### ISSUE TITLE
Aufgabe Projekt

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#34]
die Endzeit bei einer Aufgabe muss ich immer manuell eintragen, weil er setzt es automatisch auf 00:00 Uhr und somit erscheint der letzte Tage nicht in der Planung
es wäre besser wenn die Endzeit auf zBsp. 15:00 Uhr geregelt wird, oder eine Zeit ohne zwingend manuell zu bearbeiten damit es an dem Tag im Kalender auftaucht

**Comment by jziehmann** [comment]
Ich habe die Startzeit jetzt auf 9:00 und die Endzeit auf 17:00 voreingestellt.
