### ISSUE TITLE
Einsatzplanung / Kopieren der Aufgabe

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#35]
wenn wir in der Planung die Aufgabe einem zweiten Mitarbeiter zuordnen, erstellt das System keine zweite Aufgabe im Projekte, welches für uns erforderlich wäre
ansonsten müssen wir 2 Aufgaben erstellen und zuordnen

das generelle kopieren der Aufgabe im Projekt wäre auch nett ;)

**Comment by jziehmann** [comment]
Eine Aufgabe kann aus meiner Sicht nur einen Verantwortlichen haben. Beide Mitarbeiter sehen die Aufgabe in ihren Kalendern. Wenn sie abgearbeitet ist, setzt der Verantwortliche sie auf "erledigt".
