### ISSUE TITLE
Übersicht der persönlichen Aufgaben

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#37]
Ich wünsche mir einen Filter der Aufgaben nach dem Datum. So kann man direkt sehen welche Aufgabe überfällig ist oder am heutigen Tag erfüllt werden muss. Kannst du da etwas einrichten?

**Comment by jziehmann** [comment]
Ich habe jetzt die Option "Nur überfällige Aufgaben anzeigen" implementiert.
