### ISSUE TITLE
verbleibende Urlaubstage

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#39]
mir ist aufgefallen, dass bei einem neuen Eintrag die Tage aufgeschlagen statt abgezogen werden

**Comment by jziehmann** [comment]
Es wird tatsächlich nichts aufgeschlagen. Allerdings bleibt der bereits beantragte und genommene Urlaub manchmal unberücksichtigt. Ich habe jetzt eine Änderung vorgenommen. Bei mir ist der Fehler weg. Könnt ihr das bitte noch einmal ausgiebig testen? Danke.
