### ISSUE TITLE
Arbeitszeitinfo

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#42]
Die Auflistung der einzelnen Zeiten wird nicht mehr angezeigt. (ist mir heute 30.10. aufgefallen)
Ist das gewollt oder arbeitest du gerade daran?

**Comment by jziehmann** [comment]
Sorry, das hatte ich zu Debug-Zwecken rausgenommen. Ich baue es wieder ein und lade es heute Nacht wieder hoch.

Gruß

Jochen



________________________________
Von: LindaScheef ***@***.***>
Gesendet: Mittwoch, 30. Oktober 2024 16:14
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Arbeitszeitinfo (Issue #42)


Die Auflistung der einzelnen Zeiten wird nicht mehr angezeigt. (ist mir heute 30.10. aufgefallen)
Ist das gewollt oder arbeitest du gerade daran?
