### ISSUE TITLE
Mehr Infos in der Einsatzplanung bei Mausover über der Aufgabe

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#44]
für Wind Projekte:

erstmal:
PLZ des Standorts
Anlagentyp/en
Anlagenanzahl

anzeigen lassen.

Für alle Projektarten:
Beim Klick auf die Aufgabe öffnet er ja das Aufgabenfenster. Wenn in dem Aufgabenfenster durch Anklicken der Projektnummer das Projekt in einem neuen Tab angezigt würde und er das Aufgabenfenster gleichzeitig schließen würde, wäre das mega. 

Wenn noch weitere Infos wichtig werden, dann lasse ich es dich wissen :-)

**Comment by jziehmann** [comment]
Beides ist in V1.0.41 umgesetzt. Du kannst auf die Feldüberschrift "Projekt" klicken, um einen neuen Tab zu öffnen.
