### ISSUE TITLE
Idee: Übernahme von einzelnen Kontakten in der PDB ins Adressbuch M365 auf Knopfdruck

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#45]
So kann man von der PDB ins Adressbuch übernehmen. Aus dem Adressbuch heraus ist es einfacher Telefonate zu führen oder Mails zu schreiben.

**Comment by jziehmann** [comment]
Hallo Henning,


gute Idee. Kontakte exportiert man überlicherweise als Visitenkarten im standardisierten VFC-Format. Ich habe das gerade mit Outlook versucht. Outlook kann aber weder VFC-Dateien exportieren noch importieren, sondern nutzt eine proprietäres CSV-Format. Wenn ich Kontakte aus Outlook als CSV exportiere und gleich wieder importiere, gibt es jeden Kontakt zweimal. Es wird beim Import nicht überprüft, ob es den Kontakt schon gibt. Ich bin jedesmal erstaunt, wie schlecht man Dinge programmieren kann, wenn ich mir MS-Produkte ansehe. Ich suche mal nach einer Lösung.

Gruß

Jochen



________________________________
Von: HenningReiter ***@***.***>
Gesendet: Dienstag, 12. November 2024 10:40
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Idee: Übernahme von einzelnen Kontakten in der PDB ins Adressbuch M365 auf Knopfdruck (Issue #45)


So kann man von der PDB ins Adressbuch übernehmen. Aus dem Adressbuch heraus ist es einfacher Telefonate zu führen oder Mails zu schreiben.

**Comment by jziehmann** [comment]
Ich habe jetzt einen "Export"-Knopf eingebaut, der eine VCF-Datei erstellt, die man z.B. ins Adressbuch oder in seine Handy-Kontakte importieren kann.
