### ISSUE TITLE
Soll-Arbeitszeit

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#46]
Die Sollstunden lassen sich nur als ganze Stunden eintragen. Kannst du das ändern, dass ich zum Beispiel bei den 38h/Woche-Mitarbeitern die 7,6h pro Tag eintragen könnte?

**Comment by jziehmann** [comment]
Sollstunden lassen sich in der nächsten Version als Stunden und Minuten eintragen
