### ISSUE TITLE
Zeiterfassung Systemerkennung

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#48]
Können wir beim nächsten Meeting dazu sprechen, ob das System die Zeiterfassung erkennen kann und doppelte Eintragungen zur gleichen Zeit am gleichen Tag warnen kann? ich muss derzeit müßig die Zeiten bei allen kontrollieren und ggf. anpassen wenn doppelt geschrieben wurde. (ja das kommt leider bei uns vor und verursacht unnötige Überstunden)

Zudem ist mir derzeit nicht ganz bewusst, ob das PDB auch erkennt wenn Urlaub oder Abwesenheit eingetragen ist, damit die Mitarbeiter dann keine Arbeitszeit eintragen können. auch das kontrolliere ich derzeit manuell.

**Comment by jziehmann** [comment]
Hallo Linda,


ich habe am Wochenende eine Kalenderansicht erstellt, in der du recht komfortabel Überlappungen erkennen kannst. Diese soll nach meiner Vorstellung auch das zukünftige Tool werden, über das die MA ihre Stunden erfassen. Es ist ja viel einfacher, im Kalender eine Zeit auszuwählen als sie einzutippen. Außerdem hat man so eine Übersicht, ob alles eingetragen wurde. Feiertage und Urlaube so wie die Soll-Arbeitszeiten zeige ich auch an. Probier das mal aus.

Gruß

Jochen

[cid:112287fd-0017-496c-926f-ec272b194ce0]

________________________________
Von: LindaScheef ***@***.***>
Gesendet: Freitag, 15. November 2024 07:26
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Zeiterfassung Systemerkennung (Issue #48)


Können wir beim nächsten Meeting dazu sprechen, ob das System die Zeiterfassung erkennen kann und doppelte Eintragungen zur gleichen Zeit am gleichen Tag warnen kann? ich muss derzeit müßig die Zeiten bei allen kontrollieren und ggf. anpassen wenn doppelt geschrieben wurde. (ja das kommt leider bei uns vor und verursacht unnötige Überstunden)

Zudem ist mir derzeit nicht ganz bewusst, ob das PDB auch erkennt wenn Urlaub oder Abwesenheit eingetragen ist, damit die Mitarbeiter dann keine Arbeitszeit eintragen können. auch das kontrolliere ich derzeit manuell.

**Comment by LindaScheef** [comment]
Hallo Jochen,
lieben Dank für deine Arbeit dazu. Das sieht schon gut aus und willst du es als einzige Erfassung einrichten oder soll es als zweite Möglichkeit zur Tabelle sein? Quasi dass der Mitarbeiter aussuchen kann wie er erfässt?
Ich kann aktuell nur meine Zeiten dort sehen, gibt es die Möglichkeit dort auch die Mitarbeiter zusätzlich einzusehen oder gezielte Mitarbeiter?
Viele Grüße
Linda

**Comment by jziehmann** [comment]
Hallo Linda,

aus meiner Sicht soll das die bevorzugte Eingabemöglichkeit sein. Die anderen können aber auch benutzt werden. Du kannst die Kalender der Kollegen unter Administration->Mitarbeiter bei den jeweiligen Mitarbeiter sehen.

**Comment by LindaScheef** [comment]
Hallo,

ich kann dir sagen, die neue Möglichkeit ist sehr gut in unserem Team angekommen und sie nutzen es sehr gern! :)
Die Ansicht in den Mitarbeitern habe ich gefunden und die werde ich dann nutzen.

Grüße
