### ISSUE TITLE
Ausrüstungsprüfungen

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#49]
Hier kann man den Mitarbeiter nicht in die Spalten zur Ansicht auswählen.

**Comment by jziehmann** [comment]
Welchen Mitarbeiter meinst du?

**Comment by HenningReiter** [comment]
alle, man kann in der Ansicht nicht sehen, wem die Ausrüstung zugeordnet ist.
Steffen möchte das gerne sehen können in der Ansicht

**Comment by LindaScheef** [comment]
Hallo, ich denke du kannst diese Anfrage als "completed" sehen. Die neue Kalenderübersicht hat die Frage erledigt. :)

**Comment by jziehmann** [comment]
Alles klar. Ich füge die Spalte in die Tabelle ein.
