### ISSUE TITLE
Block für nachträgliches Ändern der Arbeitszeiten

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#50]
Hallo,

wenn ich die Arbeitszeiten des Vormonats ziehe, können die Mitarbeiter Änderungen weiterhin vornehmen, welche mir nicht auffallen würde. Oder bekomme ich dazu eine Mitteilung, wenn die Stunden als 'verrechnet am' gekennzeichnet sind?
Gibt es eine Möglichkeit hier ein Hinweis-System einzurichten oder ein nachträgliches Bearbeiten zu blocken?
(ich frage gezielt nach dem Blocken, weil das unser vorheriges System konnte und es sehr praktisch war)

Viele Grüße
Linda

**Comment by jziehmann** [comment]
Hallo Linda,


klar kann ich die Bearbeitung sperren, sobald die Stunden verrechnet wurden.

Gruß

Jochen



________________________________
Von: LindaScheef ***@***.***>
Gesendet: Montag, 18. November 2024 13:25
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Block für nachträgliches Ändern der Arbeitszeiten (Issue #50)


Hallo,

wenn ich die Arbeitszeiten des Vormonats ziehe, können die Mitarbeiter Änderungen weiterhin vornehmen, welche mir nicht auffallen würde. Oder bekomme ich dazu eine Mitteilung, wenn die Stunden als 'verrechnet am' gekennzeichnet sind?
Gibt es eine Möglichkeit hier ein Hinweis-System einzurichten oder ein nachträgliches Bearbeiten zu blocken?
(ich frage gezielt nach dem Blocken, weil das unser vorheriges System konnte und es sehr praktisch war)

Viele Grüße
Linda

**Comment by LindaScheef** [comment]
Hallo Jochen,
das wäre mir sehr lieb.
Ist es dann auch geblockt neue Stunden einzutragen oder nur das Bearbeiten der verrechneten?
Viele Grüße

**Comment by jziehmann** [comment]
Ich würde nur das Bearbeiten der verrechneten sperren. Wenn jemand neue Stunden nachträgt, ist das doch nicht schlimm, oder?
