### ISSUE TITLE
Kartenansicht nach Betreiber

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#52]
Hallo Jochen, 

kannst du eine Kartenansicht nach Betreiber bereitstellen?

Viele Grüße

Henning

**Comment by jziehmann** [comment]
Das sollte auf [/machines-map ](https://pdb.8p2-data.de/machines-map) eigentlich schon so sein. Aber Betreiber und Betriebsführer sind dort vermischt. Ich habe das jetzt aufgetrennt.
