### ISSUE TITLE
Hinweise im Angebot

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#53]
Moin Jochen,

in den Hinweisen im Angebot steht immer dieser Satz, je nachdem ver das Angebot erstellt hat: Anfahrt wird aus **Aurich** kalkuliert/berechnet.

Kannst du den bitte direkt editierbar machen, oder auch ganz raus nehmen?

Und kannst du auch ein direktes Drucken als pdf ermöglichen? Würde etwas Zeit sparen

**Comment by jziehmann** [comment]
Der Hinweis erscheint, wenn als Abteilung "Technik Wind - Aurich" ausgewählt ist. Dort habt ihr den Hinweistext so eingetragen.

![image](https://github.com/user-attachments/assets/d094dd30-fa41-4148-bff5-ee918110ac01)
