### ISSUE TITLE
Bug: CRM > Kontakte > Auswählen > zu Kampagne hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#54]
Wenn man Kontakte auswählt und zu Kampagne hinzufügen möchte, erscheint im Dropdown keine Liste der angelegten Kampagnen. Gleichzeitig kann man dort auch nichts eingeben. Dringend benötigt für Erstellung der Weihnachts-Geschenkeliste.

**Comment by jziehmann** [comment]
Hallo Niklas,


das kann ich nicht nachvollziehen. Wenn ich auf einen Kontakt klicke und danach den Reiter "Kampagnen", kann ich über "Zuordnen" die Kampgane "Weihnachtspost 2024" zuordnen.

Gruß

Jochen
[cid:4ccfdc50-2e8f-4752-bef9-4c14c0001787]

[cid:d963ba23-92e5-4321-9e1f-bc533cdafa0f]

________________________________
Von: 8p2-niklaskruger ***@***.***>
Gesendet: Montag, 25. November 2024 14:48
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Bug: CRM > Kontakte > Auswählen > zu Kampagne hinzufügen funktioniert nicht (Issue #54)


Wenn man Kontakte auswählt und zu Kampagne hinzufügen möchte, erscheint im Dropdown keine Liste der angelegten Kampagnen. Gleichzeitig kann man dort auch nichts eingeben. Dringend benötigt für Erstellung der Weihnachts-Geschenkeliste.

**Comment by 8p2-niklaskruger** [comment]
Hallo Jochen, 

sorry, ich wollte aufgrund der privaten Daten keinen Screenshot anhängen. Es geht um die Listenansicht der Kontakte.

Viele Grüße
Niklas

**Comment by jziehmann** [comment]
Alles klar. Das mach ich heil.

Gruß

Jochen



________________________________
Von: 8p2-niklaskruger ***@***.***>
Gesendet: Montag, 25. November 2024 15:33
An: jziehmann/pdb-issues
Cc: Jochen Ziehmann; Comment
Betreff: Re: [jziehmann/pdb-issues] Bug: CRM > Kontakte > Auswählen > zu Kampagne hinzufügen funktioniert nicht (Issue #54)


Hallo Jochen,

sorry, ich wollte aufgrund der privaten Daten keinen Screenshot anhängen. Es geht um die Listenansicht der Kontakte.

Viele Grüße
Niklas

**Comment by jziehmann** [comment]
Ich habe bei "Weihnachtspost 2024"  ein Datum eingetragen. Jetzt erscheint die Kampagne in der Liste. Ich werde das Datumsfeld zu einem Pflichtfeld machen.

Gruß

Jochen



________________________________
Von: 8p2-niklaskruger ***@***.***>
Gesendet: Montag, 25. November 2024 15:33
An: jziehmann/pdb-issues
Cc: Jochen Ziehmann; Comment
Betreff: Re: [jziehmann/pdb-issues] Bug: CRM > Kontakte > Auswählen > zu Kampagne hinzufügen funktioniert nicht (Issue #54)


Hallo Jochen,

sorry, ich wollte aufgrund der privaten Daten keinen Screenshot anhängen. Es geht um die Listenansicht der Kontakte.

Viele Grüße
Niklas
