### ISSUE TITLE
Falsches Dateiformat für Koordinaten

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#56]
Ich möchte folgende Koordinaten für den Standort eintragen: 48.661555°N,  11.258876°E
Heraus kommt: 48,662, 11,259

Bitte hier einen String für den Feldwert hinterlegen.

**Comment by jziehmann** [comment]
Es wurden alle Stellen gespeichert, aber nicht angezeigt. Ich zeige jetzt bis zu 10 Nachkommastellen an.
