### ISSUE TITLE
Nach Update 1.0.45: Arbeitszeiten-Kalender wird nicht angezeigt, sehr lange Ladezeit der "Home"-Ansicht. EOM

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#58]

**Comment by jziehmann** [comment]
Ist das bei dir noch so? Wenn ich mich unter deinem Namen einlogge, habe ich normale Ladezeiten. Möglicherweise hat bei IONOS etwas geklemmt.

**Comment by 8p2-niklaskruger** [comment]
Nein, mittlerweile beides in Ordnung - danke!
