### ISSUE TITLE
Arbeitszeiten-Kalender

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#59]
Hallo Jochen,
die Zeiten im Kalender werden falsch dargestellt. Wenn ich eine Zeit zu Bsp. 9:00 Uhr eintrage taucht es bei 8:00 Uhr auf, dort ist auch die rote Linie für die aktuelle Zeitverfolgung.
Grüße

**Comment by jziehmann** [comment]
Hallo Linda,


das hatte ich eigentlich getestet. Ich schaue mir das gleich an.

Gruß

Jochen



________________________________
Von: LindaScheef ***@***.***>
Gesendet: Montag, 2. Dezember 2024 09:46
An: jziehmann/pdb-issues
Cc: Subscribed
Betreff: [jziehmann/pdb-issues] Arbeitszeiten-Kalender (Issue #59)


Hallo Jochen,
die Zeiten im Kalender werden falsch dargestellt. Wenn ich eine Zeit zu Bsp. 9:00 Uhr eintrage taucht es bei 8:00 Uhr auf, dort ist auch die rote Linie für die aktuelle Zeitverfolgung.
Grüße

**Comment by LindaScheef** [comment]
okay, danke.

zudem ist mir aufgefallen das wenn ich den Kalender eines Kollegen anschauen will mir mein Kalender angezeigt wird.
