### ISSUE TITLE
Arbeitszeiterfassung Projekt

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#60]
Hallo, die Kollegen struggeln ab und an wenn wir mehrere Projekte mit einem Kunden haben. Es laufen nicht genügend Details auf um das richtige Projekt zuzuordnen und die Beschriftung fehlt gänzlich nach dem Auswählen.
Können wir den Kunden und den Projektnamen/Betreff zum Zuordnen nutzen?
Lass uns dazu gern mal Donnerstag sprechen.
Danke und Grüße

**Comment by jziehmann** [comment]
Hallo Linda,

Ich zeige jetzt an allen Stellen, bei denen man ein Projekt auswählen kann, zusätzlich den Betreff an. Der Kunde wurde auch bisher schon angezeigt. Was meinst du mit "die Beschriftung fehlt gänzlich nach dem Auswählen"?

**Comment by LindaScheef** [comment]
Lieben Dank für die Bearbeitung. 
Damit meine ich, dass wenn man das entsprechende Projekt ausgewählt hat steht danach nur noch die Projektnummer.
