### ISSUE TITLE
Abrechnung nach Abteilungen

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#62]
Hallo, ich war gerade im PDB und habe mir überlegt, wie ich die Abrechnungen für 2025 gestalten kann. Können wir eine Abrechnung nach Abteilungen machen?
So wie ich das sehe wird derzeit eine Rechnungsnummer festgelegt, welche automatisch fortläuft. Ich benötige dieses System für 3 Abteilungen. Können wir sowas bitte einrichten?
Grüße

**Comment by jziehmann** [comment]
Erledigt. Ihr müsstet jetzt euren drei Abteilungen jeweils ein Nummer geben und den intialen Wert für "'Nächste Rechnungsnummer" setzen.

**Comment by jziehmann** [comment]
Die Abteilungsnummer wird der Rechnungsnummer vorangestellt. Projekte ohne Abteilung nutzen den alten Nummerkreis.
