### ISSUE TITLE
Kampagnen bearbeiten

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#64]
Zwei Themen: 
1. Duplikate finden funktioniert nicht, da in einer Kampagne dann trotzdem alle Duplikate in der Kontaktliste angezeigt werden
2. Kontakte aus Liste wieder entfernen ist sehr aufwändig und fehleranfällig, da es als Aktion nur "löschen" gibt, was aber nicht die Zuordnung, sondern den Kontakt löscht. Wenn ich einen Kontakt aus der Kampagne entfernen will, muss ich auf die Zuordnung gehen, dort ist aber chronologisch nach Zeitpunkt der Zuordnung, nicht alphabetisch sortiert. Daher folgender Vorschlag: in Kampagnenansicht sollte es nicht möglich sein, Kontakte zu löschen. Stattdessen ggf. eine andere Aktion einblenden, z.B. "aus Kampagne entfernen". Gleichzeitig sollte die Zuordnung idealerweise auch alphabetisch sortiert sein.

**Comment by HenningReiter** [comment]
Moin,
das Problem mit dem Löschen von Zuordnungen ist überall vorhanden, nicht nur bei Kampagnen. Auch bei Projekten und den zugeordneten Kontakten... Die Gefahr einer Löschung ist sehr groß!!

**Comment by jziehmann** [comment]
Die 'Löschen'-Aktion löscht bei many-to-many-Relationen auch bisher schon nicht den zugeordneten Eintrag, sondern die Zuordnung. Es wird also nicht der Kontakt gelöscht, sondern die Zuordnung des Kontakts zur Kampagne. Dasselbe gilt für alle anderen Zuordnungen (Kontakt in Projekt, Standort im Projekt, Person in Firma). Ich habe die Aktion jetzt von "Löschen" in "Zuordnung löschen" umbenannt, damit das klarer wird und sich die Leute trauen, zu löschen. Außerdem sortiere ich jetzt die Zugeordneten Einträge im Zuordnungs-Fenster alphabetisch.
