### ISSUE TITLE
Projektsuche in Arbeitszeiten deutlich weniger performant als in Projektliste

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#65]
Zum Teil werden mir die Projekte nicht angezeigt, selbst wenn ich die richtige Projektnummer eingebe. Bei Stichwörtern ist es noch weniger der Fall. Beispiel 24K6628.

**Comment by jziehmann** [comment]
Das kann ich nicht nachvollziehen. Wenn ich mich mit deinem Account einlogge, kann ich nach dem Projekt suchen. Die Abfrage dauert 700ms. Was machst du anders?

![image](https://github.com/user-attachments/assets/fe3361c9-b802-49cb-b1ba-d143c800f47d)

**Comment by jziehmann** [comment]
Was meinst du mit "Stichwörtern"?

**Comment by 8p2-niklaskruger** [comment]
Hallo Jochen, sorry, häte ich genauer erklären müssen. Ich meine das Projektsuchfeld, wenn ich einen neuen Datensatz bei Arbeitszeiten anlege. Dort findet man die Projekte z.T. nicht. Mit Stichwörtern meine ich Teilbegriffe, also z.B. den Standort.

![grafik](https://github.com/user-attachments/assets/959b35cf-c266-4684-a263-3845519b5ba7)

**Comment by jziehmann** [comment]
Du kannst Arbeitszeiten nur auf Projekte schreiben, die aktiv und dir zugeordnet sind.
Ich habe die Suche ein bisschen optimiert. Sie sollte jetzt etwas schneller laufen.
