### ISSUE TITLE
Arbeitzeit-Erfassung

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#66]
Hallo,
in der Übersicht der Soll- und Ist-Zeiten für die Projekte laufen keine Stunden für Sonntag auf.
Schaust du da bitte einmal nach? Oder willst du diese Liste nicht weiter bearbeiten wegen der neuen Übersicht?
Grüße

**Comment by jziehmann** [comment]
Hallo Linda,

was meinst du mit "laufen keine Stunden für Sonntag auf"? Meinst du diese Übersicht oder eine andere. Ich habe testweise mal 2 Stunden am Sonntag eingetragen. Die werden mir in der Übersicht links als Ist-Zeit angezeigt.

![image](https://github.com/user-attachments/assets/e28b96e1-3bbb-4c10-a491-47fdb750dc08)

**Comment by LindaScheef** [comment]
ja, diese Stunden welche auf der Tabelle und im Kalender auflaufen, laufen bei den Kollegen nicht in der Wochenansicht auf. Als Beispiel kannst du dir gern bei Steffen Bosse den 15.09.2024 anschauen. In der Übersicht der Ist-Stunden wird nichts aufgeführt.

**Comment by jziehmann** [comment]
Alles klar. Der Fehler lag darin, dass gar nicht Steffens Stunden aufsummiert wurden, sondern deine. Das habe ich jetzt geändert.
