### ISSUE TITLE
Bei Beauftragung eines Angebots wird das Auftragsdatum im Projekt nicht automatisch angepasst

### ISSUE THREAD

**Issue by 8p2-niklaskruger** [jziehmann/pdb-issues#68]

**Comment by jziehmann** [comment]
Das könnte ich machen. Aber was mache ich, wenn es mehrere Angebote und mehrere Kundenaufträge gibt? Bisher wurde im Projektauftragsdatum manuelle das Datum eingetragen, an dem das Gesamtprojekt ungefähr gestartet ist. Eigentlich ist das nur eine redundante Information, die man aus meiner Sicht auch weglassen könnte.

**Comment by jziehmann** [comment]
Ich setze jetzt das Auftragsdatum im Projekt bei der ersten Beauftragung, wenn es noch leer ist.
