### ISSUE TITLE
Ausrichtungsprüfungen

### ISSUE THREAD

**Issue by HenningReiter** [jziehmann/pdb-issues#73]
Hallo Jochen,

als Felder für die Ausrüstungsprüfungen wünscht sich unser Prüfer noch ein paar Spalten/Felder.

Wir möchten eine Übersicht exportieren können, die der angehängten Excel Tabelle entspricht.

[8.2 QHSE PSA Neu Wulmsdorf.xlsx](https://github.com/user-attachments/files/18179753/8.2.QHSE.PSA.Neu.Wulmsdorf.xlsx)

Grüße
Henning

**Comment by jziehmann** [comment]
Erledigt. Die Spalte Eingangskontrolle habe ich weggelassen, weil die Eingangskontrolle die erste Prüfung ist und sich somit verhält, wie jede spätere Prüfung auch.

![image](https://github.com/user-attachments/assets/318640ea-75db-419b-96c3-852b067b6019)
