### ISSUE TITLE
Angebot - letzte Seite, optionale Posten

### ISSUE THREAD

**Issue by LindaScheef** [jziehmann/pdb-issues#9]
optionale Posten werden bei Auftragserteilung erwähnt, können wir diese definieren oder bearbeiten? (vor dem Druck des Dokumentes)

**Comment by jziehmann** [comment]
Bitte mit Obst & Hamm abstimmen, wie optionale Positionen gehandhabt werden und wie sie im Angbot dargestellt werden sollen.
